services:
  - type: web
    name: checklist-chulucanas
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 2 --worker-class gthread --threads 4 --timeout 120 --graceful-timeout 30
    healthCheckPath: /ping
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: ADMIN_PASSWORD
        generateValue: true